apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: bitnami/postgres-exporter:latest
          env:
            - name: DATA_SOURCE_NAME
              # get values from secret named "hippo-pguser-hippo" in the same namespace
              valueFrom:
                secretKeyRef:
                  name: hippo-pguser-hippo
                  key: jdbc-uri
          ports:
            - containerPort: 9187
