apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: postgres-operator
spec:
  selector:
    app: postgres-exporter
  ports:
    - name: postgres
      protocol: TCP
      port: 9187
      targetPort: 9187
  type: ClusterIP