apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: task
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: 4.0.3
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
  releaseName: nginx-ingress
  values:
    controller:
      service:
        enabled: true
        type: LoadBalancer
        ports:
          http: 80
