apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  releaseName: nginx-ingress-controller
  targetNamespace: ingress-nginx
  values:
    controller:
      service:
        enabled: true
        type: NodePort
        ports:
          http: 80