apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: nginx-ingress
      version: 4.0.13
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: flux-system
  interval: 3m
  values:
    controller:
      service:
        type: LoadBalancer
      publishService:
        enabled: true
      ingressClassResource:
        default: true
    defaultBackend:
      enabled: true