apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  releaseName: nginx-ingress-controller
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: nginx-ingress-controller
    version: 9.10.0
  values:
    controller:
      service:
        type: LoadBalancer