apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress-controller
      version: 9.10.0
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress-controller
        namespace: flux-system
  releaseName: nginx-ingress-controller
  values:
    controller:
      service:
        enabled: true
        type: LoadBalancer
        ports:
          http: 80
