apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
        version: 9.10.1
  releaseName: nginx-ingress
  values:
    controller:
      service:
        enabled: true
        type: NodePort
        ports:
          http: 80