---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: simple-ci-cd
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s
  prune: true
  retryInterval: 3m0s
  sourceRef:
    kind: GitRepository
    name: simple-ci-cd
  targetNamespace: task
  timeout: 4m0s
  wait: true
