apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 5m
  timeout: 3m
  releaseName: nginx-ingress-controller
  valuesFrom:
  - kind: ConfigMap
    name: nginx-ingress-controller-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity