apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 25.8.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  releaseName: prometheus