apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-app-monitor
  labels:
    release: prometheus
  namespace: task
spec:
  selector:
    matchLabels:
      app: django-app
  endpoints:
    - interval: 30s
      port: app
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  labels:
    release: prometheus
  namespace: postgres-operator
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  endpoints:
    - port: postgres
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceMonitorSelector: {}

