apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-app-monitor
  namespace: task
spec:
  selector:
    matchLabels:
      app: django-app
  endpoints:
    - interval: 30s
      port: "80"
      path: /metrics